// =============================================================================
// Dot Engine - Shared Lua Autocomplete Entries
// =============================================================================

#include "LuaAutoComplete.h"

#include "../Toolbox/ToolboxManager.h"
#include "Core/Toolbox/ModuleIds.h"

namespace Dot
{

using namespace ToolboxModuleIds;

const std::vector<LuaAutoCompleteEntry>& GetLuaAutoCompleteEntries()
{
    static const std::vector<LuaAutoCompleteEntry> kEntries = {
        {"self.Position", "Vec3", "Get/set the entity's world position", "self", {kScripting}},
        {"self.Rotation", "Vec3", "Get/set the entity's rotation in degrees", "self", {kScripting}},
        {"self.Scale", "Vec3", "Get/set the entity's scale", "self", {kScripting}},
        {"self.Name", "string", "Get the entity's name", "self", {kScripting}},
        {"self.Velocity", "Vec3", "Get/set rigidbody velocity (requires RigidBody)", "self",
         {kScripting, kScriptPhysicsBindings}},
        {"self.HasRigidBody", "bool", "Check if entity has a RigidBody component", "self",
         {kScripting, kScriptPhysicsBindings}},
        {"self.HasHealth", "bool", "Check if entity has a Health component", "self", {kScripting}},
        {"self.Health", "float", "Get/set current health", "self", {kScripting}},
        {"self.MaxHealth", "float", "Get/set max health", "self", {kScripting}},
        {"self.Invulnerable", "bool", "Get/set invulnerability", "self", {kScripting}},
        {"self.DestroyOnDeath", "bool", "Get/set whether the entity is destroyed at zero health", "self", {kScripting}},
        {"self.IsDead", "bool", "Returns true when health reaches zero", "self", {kScripting}},
        {"self.HealthPercent", "float", "Get normalized health in the range 0..1", "self", {kScripting}},
        {"self.RenderLayerMask", "uint", "Get/set the entity render-layer bitmask", "self", {kScripting}},
        {"self.InWorldLayer", "bool", "Get/set whether the entity renders in the normal world layer", "self",
         {kScripting}},
        {"self.InViewmodelLayer", "bool", "Get/set whether the entity renders in the viewmodel layer", "self",
         {kScripting}},
        {"self.AttachmentEnabled", "bool", "Enable or disable the entity's attachment binding", "self", {kScripting}},
        {"self.AttachmentSocket", "string", "Get/set the current attachment socket name", "self", {kScripting}},
        {"self.AttachmentTargetMode", "string", "Read attachment mode as none, entity, or camera", "self",
         {kScripting}},
        {"self:HasSocket", "(socketName: string) -> bool", "Check whether this entity hierarchy contains a named socket",
         "self", {kScripting}},
        {"self:GetSocket", "(socketName: string) -> EntityProxy|nil",
         "Get a socket marker entity from this entity hierarchy by name", "self", {kScripting}},
        {"self:CreateSocket", "(socketName: string, localPosition?: Vec3, localRotation?: Vec3) -> EntityProxy|nil",
         "Create or reuse a child socket marker under this entity", "self", {kScripting}},
        {"self:AddForce", "(force: Vec3)", "Apply continuous force (use in OnUpdate)", "self",
         {kScripting, kScriptPhysicsBindings}},
        {"self:AddImpulse", "(impulse: Vec3)", "Apply instant impulse (immediate velocity change)", "self",
         {kScripting, kScriptPhysicsBindings}},
        {"self:ApplyDamage", "(amount: float, source?: EntityProxy) -> float",
         "Apply damage, optionally attribute a source entity, and return remaining health", "self", {kScripting}},
        {"self:Heal", "(amount: float) -> float", "Heal and return current health", "self", {kScripting}},
        {"self:RestoreFullHealth", "()", "Restore health to max health", "self", {kScripting}},
        {"self:GetEntity", "() -> Entity", "Get the raw Entity handle", "self", {kScripting}},
        {"self:AttachToEntity", "(target: EntityProxy, socketName?: string)",
         "Attach this entity to another entity, optionally using a named socket", "self", {kScripting}},
        {"self:AttachToCamera", "(socketName?: string)", "Attach this entity to the active camera or one of its sockets",
         "self", {kScripting}},
        {"self:Detach", "()", "Disable and clear the entity's current attachment binding", "self", {kScripting}},
        {"self:GetAttachmentTarget", "() -> EntityProxy|nil",
         "Get the current attachment target entity or active camera proxy", "self", {kScripting}},
        {"self:IsAttachedToCamera", "() -> bool", "Returns true when the entity is attached to the active camera",
         "self", {kScripting}},
        {"self:MoveTo", "(target: Vec3, options?: table, callback?: function) -> NavigationMoveHandle",
         "Start a navmesh move toward the target. Optional callback receives (status, handle) when the move completes.",
         "self", {kScripting, kScriptNavigationBindings}},
        {"self:StopMove", "()", "Cancel the entity's active navmesh move if one exists", "self",
         {kScripting, kScriptNavigationBindings}},
        {"self:IsMoving", "() -> bool", "Returns true while a nav move is pending or actively moving", "self",
         {kScripting, kScriptNavigationBindings}},
        {"self:GetMoveStatus", "() -> string", "Returns idle, pending, moving, succeeded, failed, or cancelled", "self",
         {kScripting, kScriptNavigationBindings}},
        {"self:HasLineOfSight", "(target: EntityProxy|Vec3, options?: table) -> bool",
         "Check whether world geometry or colliders block a straight sightline to the target.", "self",
         {kScripting, kScriptPerceptionBindings}},
        {"self:CanSee", "(target: EntityProxy|Vec3, options?: table) -> bool",
         "Check field-of-view, optional max distance, and line of sight against the target.", "self",
         {kScripting, kScriptPerceptionBindings}},
        {"self:GetEntitiesInRadius", "(radius: float, options?: table) -> table",
         "Return nearby entities around self, sorted nearest-first.", "self",
         {kScripting, kScriptPerceptionBindings}},
        {"self:Destroy", "()", "Destroy this entity", "self", {kScripting}},

        {"Input.IsKeyDown", "(key: string) -> bool",
         "Returns true while key is held. Keys: A-Z, 0-9, Space, Shift, Tab, etc.", "Input", {kScripting}},
        {"Input.IsKeyPressed", "(key: string) -> bool", "Returns true only on the frame the key was pressed", "Input",
         {kScripting}},
        {"Input.IsKeyReleased", "(key: string) -> bool",
         "Returns true only on the frame the key was released", "Input", {kScripting}},
        {"Input.IsMouseButtonDown", "(button: int) -> bool", "Check mouse button. 0=left, 1=right, 2=middle", "Input",
         {kScripting}},
        {"Input.IsMouseButtonPressed", "(button: int) -> bool", "True only on frame button was pressed", "Input",
         {kScripting}},
        {"Input.IsMouseButtonReleased", "(button: int) -> bool", "True only on frame button was released", "Input",
         {kScripting}},
        {"Input.GetMousePosition", "() -> Vec2", "Get current mouse position in screen coordinates", "Input",
         {kScripting}},
        {"Input.GetViewportMousePosition", "() -> Vec2", "Get mouse position relative to viewport", "Input",
         {kScripting}},
        {"Input.IsMouseInViewport", "() -> bool", "Check if mouse is inside the viewport", "Input", {kScripting}},
        {"Input.GetMouseDelta", "() -> Vec2", "Get mouse movement since last frame", "Input", {kScripting}},

        {"Camera.GetPosition", "() -> Vec3", "Get the camera's world position", "Camera", {kScripting}},
        {"Camera.GetForward", "() -> Vec3", "Get the camera's forward direction vector", "Camera", {kScripting}},
        {"Camera.GetUp", "() -> Vec3", "Get the camera's up direction vector", "Camera", {kScripting}},
        {"Camera.GetRight", "() -> Vec3", "Get the camera's right direction vector", "Camera", {kScripting}},
        {"Camera.ScreenToWorldRay", "(x, y) -> {origin, direction}",
         "Convert viewport coords to world ray for raycasting", "Camera", {kScripting}},
        {"Camera.WorldLayerMask", "uint", "Bitmask constant for the normal world render layer", "Camera",
         {kScripting}},
        {"Camera.ViewmodelLayerMask", "uint", "Bitmask constant for the viewmodel render layer", "Camera",
         {kScripting}},
        {"Camera.IsViewmodelPassEnabled", "() -> bool", "Check whether the active camera renders the viewmodel pass",
         "Camera", {kScripting}},
        {"Camera.SetViewmodelPassEnabled", "(enabled: bool)", "Enable or disable the active camera's viewmodel pass",
         "Camera", {kScripting}},
        {"Camera.GetViewmodelFov", "() -> float", "Get the active camera's viewmodel FOV in degrees", "Camera",
         {kScripting}},
        {"Camera.SetViewmodelFov", "(fov: float)", "Set the active camera's viewmodel FOV in degrees", "Camera",
         {kScripting}},
        {"Camera.GetViewmodelNearPlane", "() -> float", "Get the active camera's viewmodel near clip distance",
         "Camera", {kScripting}},
        {"Camera.SetViewmodelNearPlane", "(nearPlane: float)",
         "Set the active camera's viewmodel near clip distance", "Camera", {kScripting}},
        {"Camera.IsViewmodelLayerVisible", "() -> bool",
         "Check whether the active camera includes the viewmodel layer in its render mask", "Camera",
         {kScripting}},
        {"Camera.SetViewmodelLayerVisible", "(visible: bool)",
         "Toggle whether the active camera renders entities on the viewmodel layer", "Camera", {kScripting}},
        {"Camera.HasSocket", "(socketName: string) -> bool", "Check whether the active camera has a named socket",
         "Camera", {kScripting}},
        {"Camera.GetSocket", "(socketName: string) -> EntityProxy|nil",
         "Get a named socket marker entity from the active camera hierarchy", "Camera", {kScripting}},
        {"Camera.CreateSocket", "(socketName: string, localPosition?: Vec3, localRotation?: Vec3) -> EntityProxy|nil",
         "Create or reuse a child socket marker under the active camera", "Camera", {kScripting}},

        {"Timer.After", "(seconds: float, callback: function) -> int",
         "Call function once after delay. Returns timer ID", "Timer", {kScripting}},
        {"Timer.Every", "(seconds: float, callback: function) -> int",
         "Call function repeatedly. Returns timer ID", "Timer", {kScripting}},
        {"Timer.Cancel", "(id: int)", "Cancel a timer by its ID", "Timer", {kScripting}},
        {"Timer.CancelAll", "()", "Cancel all active timers", "Timer", {kScripting}},

        {"Physics.Raycast", "(origin: Vec3, direction: Vec3, maxDist: float, layerMask?: uint) -> table|nil",
         "Cast ray and return hit info: {point, normal, distance, entity}. Optional mask filters layers.", "Physics",
         {kScripting, kScriptPhysicsBindings}},
        {"Physics.OverlapSphere", "(center: Vec3, radius: float, layerMask?: uint) -> table",
         "Find colliders overlapping a sphere. Optional mask filters layers.", "Physics",
         {kScripting, kScriptPhysicsBindings}},
        {"Physics.CheckSphere", "(center: Vec3, radius: float, layerMask?: uint) -> bool",
         "Check whether any collider overlaps a sphere volume. Optional mask filters layers.", "Physics",
         {kScripting, kScriptPhysicsBindings}},
        {"Physics.GetLayerIndex", "(name: string) -> int",
         "Look up a project collision layer slot by name. Returns -1 if missing.", "Physics",
         {kScripting, kScriptPhysicsBindings}},
        {"Physics.GetLayerMask", "(name: string) -> uint",
         "Look up a project collision layer mask bit by name. Returns 0 if missing.", "Physics",
         {kScripting, kScriptPhysicsBindings}},

        {"Perception.HasLineOfSight", "(observer: EntityProxy|Vec3, target: EntityProxy|Vec3, options?: table) -> bool",
         "Check whether a straight sightline is unobstructed by world geometry or colliders.", "Perception",
         {kScripting, kScriptPerceptionBindings}},
        {"Perception.CanSee", "(observer: EntityProxy, target: EntityProxy|Vec3, options?: table) -> bool",
         "Check field-of-view, optional max distance, and line of sight.", "Perception",
         {kScripting, kScriptPerceptionBindings}},
        {"Perception.GetEntitiesInRadius", "(center: Vec3, radius: float, options?: table) -> table",
         "Return nearby entities around a point, sorted nearest-first.", "Perception",
         {kScripting, kScriptPerceptionBindings}},

        {"Navigation.IsAvailable", "() -> bool", "Returns true when a navmesh is built and ready for queries",
         "Navigation", {kScripting, kScriptNavigationBindings}},
        {"Navigation.FindPathAsync", "(start: Vec3, goal: Vec3, options?: table) -> NavigationPathRequest",
         "Queue an async path query. Handle exposes Status, IsDone, Succeeded, and Path.", "Navigation",
         {kScripting, kScriptNavigationBindings}},
        {"Navigation.FindPath", "(start: Vec3, goal: Vec3, options?: table) -> table|nil",
         "Run a synchronous path query and return an array of Vec3 path points, or nil on failure.", "Navigation",
         {kScripting, kScriptNavigationBindings}},
        {"NavigationPathRequest.Status", "string", "Current async path state: pending, succeeded, failed, or cancelled",
         "Navigation", {kScripting, kScriptNavigationBindings}},
        {"NavigationPathRequest.IsDone", "bool", "Returns true once the async path query has finished", "Navigation",
         {kScripting, kScriptNavigationBindings}},
        {"NavigationPathRequest.Succeeded", "bool", "Returns true when the async path query completed successfully",
         "Navigation", {kScripting, kScriptNavigationBindings}},
        {"NavigationPathRequest.Path", "table", "Resolved path as a Lua array of Vec3 path points", "Navigation",
         {kScripting, kScriptNavigationBindings}},
        {"NavigationMoveHandle.Status", "string", "Current move state: pending, moving, succeeded, failed, or cancelled",
         "Navigation", {kScripting, kScriptNavigationBindings}},
        {"NavigationMoveHandle.IsDone", "bool", "Returns true once the nav move has finished", "Navigation",
         {kScripting, kScriptNavigationBindings}},
        {"NavigationMoveHandle.Succeeded", "bool", "Returns true when the nav move completed successfully", "Navigation",
         {kScripting, kScriptNavigationBindings}},
        {"NavigationMoveHandle.Path", "table", "Resolved move path as a Lua array of Vec3 path points", "Navigation",
         {kScripting, kScriptNavigationBindings}},

        {"World.FindByName", "(name: string) -> EntityProxy|nil", "Find an entity by its name", "World", {kScripting}},
        {"World.GetEntitiesWithName", "() -> table", "Get all entities that have names", "World", {kScripting}},
        {"World.Spawn", "(name: string) -> EntityProxy", "Create new entity with name and transform", "World",
         {kScripting}},
        {"World.SpawnAt", "(name, position) -> EntityProxy", "Create entity at position", "World", {kScripting}},
        {"World.SpawnPrimitive", "(name, primitiveType, position?) -> EntityProxy",
         "Create a renderable primitive entity such as Cube, Sphere, Cylinder, Plane, Cone, or Capsule.", "World",
         {kScripting}},
        {"World.DestroyEntity", "(entity: EntityProxy)", "Destroy an entity", "World", {kScripting}},

        {"Log.Info", "(message: string)", "Log an info message to console", "Log", {kScripting}},
        {"Log.Warn", "(message: string)", "Log a warning message to console", "Log", {kScripting}},
        {"Log.Error", "(message: string)", "Log an error message to console", "Log", {kScripting}},

        {"Vec3", "(x, y, z) -> Vec3", "Create a new 3D vector", "Math", {kScripting}},
        {"Vec3.x", "float", "X component of the vector", "Math", {kScripting}},
        {"Vec3.y", "float", "Y component of the vector", "Math", {kScripting}},
        {"Vec3.z", "float", "Z component of the vector", "Math", {kScripting}},
        {"Vec3:Length", "() -> float", "Get the length of the vector", "Math", {kScripting}},
        {"Vec3:Normalized", "() -> Vec3", "Get a normalized copy of this vector", "Math", {kScripting}},
        {"Vec3:Dot", "(other: Vec3) -> float", "Dot product with another vector", "Math", {kScripting}},
        {"Math.Lerp", "(a, b, t) -> float", "Linear interpolation between a and b", "Math", {kScripting}},
        {"Math.LerpVec3", "(a, b, t) -> Vec3", "Lerp between two Vec3 values", "Math", {kScripting}},
        {"Math.Clamp", "(value, min, max) -> float", "Clamp value within min/max range", "Math", {kScripting}},
        {"Math.Random", "() -> float", "Random number between 0 and 1", "Math", {kScripting}},
        {"Math.RandomRange", "(min, max) -> float", "Random float in range", "Math", {kScripting}},
        {"Math.RandomInt", "(min, max) -> int", "Random integer in range (inclusive)", "Math", {kScripting}},
        {"Math.Sign", "(value) -> float", "Returns -1, 0, or 1", "Math", {kScripting}},
        {"Math.Abs", "(value) -> float", "Absolute value", "Math", {kScripting}},
        {"Math.Distance", "(a, b) -> float", "Distance between two Vec3 points", "Math", {kScripting}},

        {"Tween.To", "(from, to, duration, callback) -> id", "Animate value over time, callback(value)", "Tween",
         {kScripting}},
        {"Tween.Cancel", "(id: int)", "Cancel a running tween", "Tween", {kScripting}},

        {"function OnStart", "()", "Called once when play mode starts", "Lifecycle", {kScripting}},
        {"function OnUpdate", "(dt)", "Called every frame. dt = delta time in seconds", "Lifecycle", {kScripting}},
        {"function OnDestroy", "()", "Called when play mode stops or entity is destroyed", "Lifecycle", {kScripting}},
        {"function OnCollisionEnter", "(other, hit)", "Called when a non-trigger collision starts", "Lifecycle",
         {kScripting, kScriptPhysicsBindings}},
        {"function OnCollisionStay", "(other, hit)", "Called every frame while a non-trigger collision persists",
         "Lifecycle", {kScripting, kScriptPhysicsBindings}},
        {"function OnCollisionExit", "(other, hit)", "Called when a non-trigger collision ends", "Lifecycle",
         {kScripting, kScriptPhysicsBindings}},
        {"function OnTriggerEnter", "(other, hit)", "Called when a trigger overlap starts", "Lifecycle",
         {kScripting, kScriptPhysicsBindings}},
        {"function OnTriggerStay", "(other, hit)", "Called every frame while a trigger overlap persists", "Lifecycle",
         {kScripting, kScriptPhysicsBindings}},
        {"function OnTriggerExit", "(other, hit)", "Called when a trigger overlap ends", "Lifecycle",
         {kScripting, kScriptPhysicsBindings}},
        {"function OnDamaged", "(amount, source)", "Called when Health receives damage. source is the attacking entity if provided.", "Lifecycle", {kScripting}},
        {"function OnDeath", "(source)", "Called once when Health reaches zero. source is the attacking entity if provided.", "Lifecycle", {kScripting}},
        {"function OnMoveFinished", "(status, handle)", "Called when a navmesh MoveTo request finishes, fails, or is cancelled.",
         "Lifecycle", {kScripting, kScriptNavigationBindings}},

        {"local", "", "Declare a local variable", "Lua"},
        {"function", "", "Declare a function", "Lua"},
        {"if", "condition then ... end", "Conditional statement", "Lua"},
        {"for", "i = 1, n do ... end", "For loop", "Lua"},
        {"while", "condition do ... end", "While loop", "Lua"},
        {"return", "", "Return from function", "Lua"},
        {"true", "bool", "Boolean true value", "Lua"},
        {"false", "bool", "Boolean false value", "Lua"},
        {"nil", "", "Null/nothing value", "Lua"},
        {"print", "(value)", "Print a value to console", "Lua"},
        {"tostring", "(value) -> string", "Convert value to string", "Lua"},
    };

    return kEntries;
}

bool IsLuaAutoCompleteEntryVisible(const LuaAutoCompleteEntry& entry)
{
    for (const std::string& moduleId : entry.requiredModules)
    {
        if (!ToolboxManager::Get().IsModuleEnabled(moduleId))
            return false;
    }

    return true;
}

} // namespace Dot
